
services:
  db:
    image: postgres:16-alpine
    container_name: tcc-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backloan

    volumes:
      - db_data:/var/lib/postgresql/data

  backloan:
    build:
      context: ./Backloan
    container_name: tcc-backend
    restart: always
    environment:
    
      DATABASE_URL: postgresql://postgres:postgres@db:5432/backloan?schema=public

    depends_on:
      - db
    ports:
      - "3000:3000" 

  frontlloan:
    build:
      context: ./Frontlloan
    container_name: tcc-frontend
    restart: always
    depends_on:
      - backloan
    ports:
      - "80:80"

volumes:
  db_data:
